version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: inventory_system_web
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: inventory_system_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      APACHE_ALLOW_OVERRIDE: Yes
    ports:
      - "8081:80"  # phpMyAdmin accessible at http://localhost:8081
    volumes:
      - ./phpmyadmin/.htaccess:/var/www/html/.htaccess
      - ./phpmyadmin/.htpasswd:/etc/phpmyadmin/.htpasswd
    depends_on:
      - db
    networks:
      - default

volumes:
  db_data:
