version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: inventory_system_web
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - inventory-system-net

  db:
    image: mysql:8.0
    container_name: inventory_system_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inventory-system-net

volumes:
  db_data:

networks:
  inventory-system-net:
